---

build-push-ssllabs:
  variables:
    STACK: "engine-ssllabs"
    FOLDER_PATH: "engines/ssllabs"
    PORT: 5004
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

test-build-ssllabs:
  variables:
    STACK: "engine-ssllabs"
    FOLDER_PATH: "engines/ssllabs"
    PORT: 5004
  extends: .test-build
  
# run-job-ssllabs:
#   variables:
#     STACK: "engine-ssllabs"
#     FOLDER_PATH: "engines/ssllabs"
#     PORT: 5004
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
