---

build-push-owl_code:
  variables:
    STACK: "engine-owl_code"
    FOLDER_PATH: "engines/owl_code"
    PORT: 5013
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

test-build-owl_code:
  variables:
    STACK: "engine-owl_code"
    FOLDER_PATH: "engines/owl_code"
    PORT: 5013
  extends: .test-build
  
# run-job-owl_code:
#   variables:
#     STACK: "engine-owl_code"
#     FOLDER_PATH: "engines/owl_code"
#     PORT: 5013
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
