---

build-push-nessus:
  variables:
    STACK: "engine-nessus"
    FOLDER_PATH: "engines/nessus"
    PORT: 5002
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

# run-job-nessus:
#   variables:
#     STACK: "engine-nessus"
#     FOLDER_PATH: "engines/nessus"
#     PORT: 5002
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
