---

build-push-censys:
  variables:
    STACK: "engine-censys"
    FOLDER_PATH: "engines/censys"
    PORT: 5110
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

test-build-censys:
  variables:
    STACK: "engine-censys"
    FOLDER_PATH: "engines/censys"
    PORT: 5110
  extends: .test-build

# run-job-censys:
#   variables:
#     STACK: "engine-censys"
#     FOLDER_PATH: "engines/censys"
#     PORT: 5110
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
