---

build-push-droopescan:
  variables:
    STACK: "engine-droopescan"
    FOLDER_PATH: "engines/droopescan"
    PORT: 5021
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

test-build-droopescan:
  variables:
    STACK: "engine-droopescan"
    FOLDER_PATH: "engines/droopescan"
    PORT: 5021
  extends: .test-build
  
# run-job-droopescan:
#   variables:
#     STACK: "engine-droopescan"
#     FOLDER_PATH: "engines/droopescan"
#     PORT: 5021
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
