---

build-push-urlvoid:
  variables:
    STACK: "engine-urlvoid"
    FOLDER_PATH: "engines/urlvoid"
    PORT: 5008
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

test-build-urlvoid:
  variables:
    STACK: "engine-urlvoid"
    FOLDER_PATH: "engines/urlvoid"
    PORT: 5008
  extends: .test-build
  
# run-job-urlvoid:
#   variables:
#     STACK: "engine-urlvoid"
#     FOLDER_PATH: "engines/urlvoid"
#     PORT: 5008
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
