---

build-push-openvas:
  variables:
    STACK: "engine-openvas"
    FOLDER_PATH: "engines/openvas"
    PORT: 5016
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

# run-job-openvas:
#   variables:
#     STACK: "engine-openvas"
#     FOLDER_PATH: "engines/openvas"
#     PORT: 5016
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
