---

build-push-wpscan:
  variables:
    STACK: "engine-wpscan"
    FOLDER_PATH: "engines/wpscan"
    PORT: 5023
  before_script:
    - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
    ### Issue with variable expansion in variable section
  extends: .build-push

# run-job-wpscan:
#   variables:
#     STACK: "engine-wpscan"
#     FOLDER_PATH: "engines/wpscan"
#     PORT: 5023
#   before_script:
#     - VERSION=$(cat $CI_PROJECT_DIR/$FOLDER_PATH/VERSION | cut -d " " -f1)
#     ### Issue with variable expansion in variable section
#   extends: .run-job
